name: delivery_manager_flutter
description: A Flutter application for managing delivery operations using OpenStreetMap.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/locales/en.json
    - assets/map_styles/osm_map_style.json