name: shared_lib
description: Shared library for delivery app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  uuid: ^3.0.7
  flutter_stripe: ^9.3.0
  flutter_chat_ui: ^1.6.9
  socket_io_client: ^2.0.2
  charts_flutter: ^0.12.0
  pdf: ^3.10.4
  path_provider: ^2.1.0
  url_launcher: ^6.1.12
  share_plus: ^7.1.0
  geolocator: ^10.0.0
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2