name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.16.0'
  NODE_VERSION: '20.x'
  FLUTTER_ANALYTICS: false

jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate cache key
      id: cache-key
      shell: bash
      run: echo "value=${RUNNER_OS}-flutter-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
    
    - name: Configure Flutter
      run: |
        flutter config --no-analytics
        flutter --disable-analytics
        echo "FLUTTER_ANALYTICS=false" >> $GITHUB_ENV
