name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build API
      run: npm run build

  build-delivery-manager:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./delivery_manager_flutter

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build web
      run: flutter build web
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: delivery-manager-web
        path: delivery_manager_flutter/build/web/
        
  build-driver-app:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./driver_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build Android APK
      run: flutter build apk --release
    
    - name: Upload Android build
      uses: actions/upload-artifact@v4
      with:
        name: driver-app-android
        path: driver_app/build/app/outputs/flutter-apk/app-release.apk

  build-restaurant-app:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./restaurant_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build web
      run: flutter build web
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: restaurant-app-web
        path: restaurant_app/build/web/

  build-customer-app:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./customer_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build web
      run: flutter build web
    
    - name: Build Android APK
      run: flutter build apk --release
    
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: customer-app-web
        path: customer_app/build/web/
    
    - name: Upload Android build
      uses: actions/upload-artifact@v4
      with:
        name: customer-app-android
        path: customer_app/build/app/outputs/flutter-apk/app-release.apk